language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit tests
  - vendor/bin/paratest tests
